enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  ForgotPassword = 'ForgotPassword',
 CREATE_PASSWORD = 'CREATE_PASSWORD',
  OTP_SCREEN = 'OTP_SCREEN',
  ASK_LOCATION ='ASK_LOCATION',
  LOCATION_SCREEN ='LOCATION_SCREEN',
  BOTTOM_TAB ='BOTTOM_TAB',
  Splash='Splash',

  // Tab Screens
  HOME_SCREEN='HOME_SCREEN',
  BATTING_HISTORY = 'BATTING_HISTORY',
  SETTING_SCREEN ='SETTING_SCREEN',
  AddProfilePicture='AddProfilePicture',

//profile

EDIT_PROFILE ='EDIT_PROFILE',
CHANGE_PASSWORD ='CHANGE_PASSWORD',
FAQ ="FAQ",
ABOUT_US= "ABOUT_US",
PRIVACY_POLICY ='PRIVACY_POLICY',
NOTIFICATION_SCREEN='NOTIFICATION_SCREEN',
WALLETE_SCREEN ="WALLETE_SCREEN"




  
}

export default ScreenNameEnum;
